---
title: "ECIV 542 (Fall 2026) Schedule"
format: html
---

::: panel-tabset
## Schedule (Fall'26)

| Week                    | Class | Date          | Topic [^1]              | Notes               | Slides        |
|:-----------------------:|:-----:|---------------|-------------------------|:-------------------:|:-------------:|
| [1](/weeks/week-1.html) |   01  | Wed, Aug 19   |                         | {{< fa circle-x >}} | [🖥]()        |
| [2](/weeks/week-1.html) |   02  | Mon, Aug 24   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   03  | Wed, Aug 26   |                         | {{< fa circle-x >}} | [🖥]()        |
| [3](/weeks/week-1.html) |   04  | Mon, Aug 31   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   05  | Wed, Sep 02   |                         | {{< fa circle-x >}} | [🖥]()        |
| [4](/weeks/week-1.html) |       | Mon, Sep 07   |NO CLASS (LABOR DAY)     | {{< fa circle-x >}} | [🖥]()        |
|                         |   06  | Wed, Sep 09   |                         | {{< fa circle-x >}} | [🖥]()        |
| [5](/weeks/week-1.html) |   07  | Mon, Sep 14   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   08  | Wed, Sep 16   |                         | {{< fa circle-x >}} | [🖥]()        |
| [6](/weeks/week-1.html) |   09  | Mon, Sep 21   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   10  | Wed, Sep 23   |                         | {{< fa circle-x >}} | [🖥]()        |
| [7](/weeks/week-1.html) |   11  | Mon, Sep 28   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   12  | Wed, Sep 30   |                         | {{< fa circle-x >}} | [🖥]()        |
| [8](/weeks/week-1.html) |   13  | Mon, Oct 05   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   14  | Wed, Oct 07   |                         | {{< fa circle-x >}} | [🖥]()        |
| [9](/weeks/week-1.html) |   15  | Mon, Oct 12   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   16  | Wed, Oct 14   |                         | {{< fa circle-x >}} | [🖥]()        |
|[10](/weeks/week-1.html) |   17  | Mon, Oct 19   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   18  | Wed, Oct 21   |                         | {{< fa circle-x >}} | [🖥]()        |
|[11](/weeks/week-1.html) |   19  | Mon, Oct 26   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   20  | Wed, Oct 28   |                         | {{< fa circle-x >}} | [🖥]()        |
|[12](/weeks/week-1.html) |   21  | Mon, Nov 02   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   22  | Wed, Nov 04   |                         | {{< fa circle-x >}} | [🖥]()        |
|[13](/weeks/week-1.html) |   23  | Mon, Nov 09   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   24  | Wed, Nov 11   |                         | {{< fa circle-x >}} | [🖥]()        |
|[14](/weeks/week-1.html) |   25  | Mon, Nov 16   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   26  | Wed, Nov 18   |                         | {{< fa circle-x >}} | [🖥]()        |
|[15](/weeks/week-1.html) |       | Mon, Nov 23   |NO CLASS (Thanksgiving)  | {{< fa circle-x >}} | [🖥]()        |
|                         |       | Wed, Nov 25   |NO CLASS (Thanksgiving)  | {{< fa circle-x >}} | [🖥]()        |
|[16](/weeks/week-1.html) |   27  | Mon, Nov 30   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |   28  | Wed, Dec 02   |                         | {{< fa circle-x >}} | [🖥]()        |
|[17](/weeks/week-1.html) |   29  | Wed, Dec 04   |                         | {{< fa circle-x >}} | [🖥]()        |
|                         |       | Wed, Dec xx   | Final Exam Day          | {{< fa circle-x >}} | [🖥]()        |
|[18](/weeks/week-1.html) |       | Wed, Dec 14   | Fall Commencement       | {{< fa circle-x >}} | [🖥]()        |

[^1] Subject to change

## Homework & Lab

| Date          | Type       | Status              | Topic                      | Due Date & Time        | Submit Using  |
|:--------------|------------|:-------------------:|:--------------------------:|:----------------------:|:-------------:|
| Aug 31, 2026  | Homework   | Not Assigned        | Class topics of wk: 1-3    | Sep 7, 2026 by 11:59PM | Blackboard    |

## Exams

| Date          | Type    | Method                 | Status        | Topic                      | Due Date & Time        |
|:--------------|---------|:----------------------:|:-------------:|:--------------------------:|:----------------------:|
| ------, xxxx  | Exam 01 | In-class; Closed Book  | Not Assigned  | Class topics of wk: 1-3    | Sep 7, 2026 by 11:59PM |


:::
